### ISSUE TITLE
Zulu Mac OS X JRE archive not detected

### ISSUE THREAD

**Issue by anuraaga** [actions/setup-java#111]
I recently tried to specify Java 8.0.275 to setup for a fix to a [JDK bug](http://openjdk.5641.n7.nabble.com/Bug-3812-New-IcedTea7-Backport-JDK-8250861-quot-Crash-in-MinINode-Ideal-PhaseGVN-bool-td431647.html)

But it doesn't work with this message `Error: No valid download found for version 8.0.275 and package jre. Check https://static.azul.com/zulu/bin/ for a list of valid versions or download your own jdk file and add the jdkFile argument.

This seems to be because [zulu](https://static.azul.com/zulu/bin/) only publishes a zip file of the JRE for macosx, not a tar.gz. Perhaps it's a bug in zulu's packaging, but either way it seems reasonable to handle this filename in this action.

**Comment by giltene** [comment]
I think the issue here was around the timing of the explicit specification of the just-released 8u275: the switch to specifying 8u275 (and the opening of this issue) happened between the CDN publication of 8u275 packages for some package types (e.g. the JDK) and the publication of the same update level for the MacOS jre package type. As both are now published, the issue itself does not appear to reproduce, Specifically, the MacOS jre for 8u275 appears to be currently working (see e.g. https://github.com/giltene/jdkTestingMatrix/runs/1498855808?check_suite_focus=true).

It is worth noting that explicitly requiring a just-released update level, prior to verifying that the update is already available for the platform and package type involved, will be susceptible to this sort of initial timing window difference between available package types (and platforms) by definition. When updates are rolled out in a distribution, they will sometimes appear “nearly instantaneously” for all platforms and package types, as is often the case in planned quarterly updates that are often ready to go ahead of time, such that the timing window for seeing a difference in the latest update levels of different package types is small. But when unplanned updates like 8u275 and 8u265 occur, where an urgent intra-quarter update is getting rolled out to address a serious enough regression in the previously rolled out OpenJDK update (in these examples, 8u272 and 8u262 respectively, both of which, unfortunately, included production-affecting regressions in the upstream project, leading to the releases of 8u265 and 8u275), a timing gap is more likely to show up during the rollout, as holding back some packages (e.g. JDKs in this case) until all packages (e.g. all JREs) are fully tested is perceived as causing more harm (delayed availability of a critical fix) than good (alignment in publication timing across all package types).

**Comment by anuraaga** [comment]
@giltene Thanks for the response and sorry for the delay in replying. I guess it was just a combination of unfortunate events :) Our build was failing frequently due to that JDK bug so we needed to bump before it'd generally be ready. But I think this is not a big deal. Thanks!
