### ISSUE TITLE
'adopt' is ambigous

### ISSUE THREAD

**Issue by bmarwell** [actions/setup-java#160]
**Description:**

Distribution name 'adopt' is ambigous.
There are two VM implementations available under this name, Hotspot and OpenJ9.

**Task version:**

v2

**Platform:**
- [X] Ubuntu
- [X] macOS
- [X] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  

`distribution: adopt`

**Expected behavior:**

Expected adopt-hotspot and adopt-openj9 instead.

**Actual behavior:**

One of them is chosen, I do not know which one – probably hotspot?

**Comment by dmitry-shibanov** [comment]
Hello @bmarwell. Currently the action supports only hotspot releases and "adopt" references hotspot binaries. We have an active [pull request](https://github.com/actions/setup-java/pull/155) to add support for openj9 implementation.

**Comment by maxim-lobanov** [comment]
Merged PR and released version `v2.1.0` [Link](https://github.com/actions/setup-java/releases/tag/v2.1.0). No need to bump major version since there are no breaking changes.
Going to update `v2` tag to point to `v2.1.0` tomorrow. Will be appreciate for any testing and confirmation that it works as expected.

**Comment by dmitry-shibanov** [comment]
Hello @bmarwell, pull request was merged and v2 tag was also updated. I'm closing the issue. If you have any concerns feel free to reopen the issue.
