### ISSUE TITLE
Add support for Maven settings to support mTLS authentication towards mirror repository

### ISSUE THREAD

**Issue by tveon** [actions/setup-java#283]
**Description:**
Add additional configuration properties to allow configuring maven to perform mTLS authentication towards the specific Maven repository.
AFAICT we need a number of properties to make this work...

Firstly we need to configure Maven to use our internal repository as a mirror, with username and password authentication - so we need to be able to specify the `.m2/settings.xml`. 

To keep the password encrypted, we also need to be able to specify the `.m2/settings-security.xml`.

Thirdly, we need to be able to setup the `MAVEN_OPTS` environment variable for Maven to pick up the the certificates used for mTLS like: `-Djavax.net.ssl.keyStore=${p12Path} -Djavax.net.ssl.keyStoreType=pkcs12 -Djavax.net.ssl.keyStorePassword=${p12Password}`

Finally, we need to add the CA certificate used to issue the server-certificate to the JVAM trustore.

Following the order of the above, I'd suggest adding the following 5 properties:
```
    maven-settings-b64: ${{ secrets.MAVEN_SETTINGS }}
    maven-security-settings-b64: ${{ secrets.MAVEN_SECURITY }} 
    maven-keystore-p12-b64: ${{ secrets.MAVEN_P12 }}
    maven-keystore-password: ${{ secrets.MAVEN_P12_PASSWORD }}
    maven-ca-cert-b64: ${{ secrets.MTLS_CACERT }}
```

**Justification:**
Our company policy mandates using the internal Maven repository - which is also a necessity to access internal libraries.
Maven has mTLS as one of the standard security-measures, so it is reasonable to also support it for CI via GitHub Actions.

**Are you willing to submit a PR?**
I'd like to give it a try, if we can agree to the solution. 🙂

**Comment by dmitry-shibanov** [comment]
Hello @tveon. Thank you for your report. We'll investigate the issue and notify you of our decision

**Comment by tveon** [comment]
Hi @dmitry-shibanov. Any update on this?

**Comment by tveon** [comment]
Hi @brcrista. It would not be impossible to handle Maven configuration in another step - but that can said about most things. 🙂 

Having it as part of the action would ensure that updates to how `setup-java` configures Maven would not conflict with modifications made in a separate step - e.g. accidentially producing a malformed `settings.xml` file.
But primarily, it would simplify rolling out GitHub Actions as the standard CI for our teams, as it would make the experience closer to the preconfigured versions of Java and Maven they get on Jenkins.

**Comment by brcrista** [comment]
Thanks.  Based on the inputs you proposed:

```yml
    maven-settings-b64: ${{ secrets.MAVEN_SETTINGS }}
    maven-security-settings-b64: ${{ secrets.MAVEN_SECURITY }} 
    maven-keystore-p12-b64: ${{ secrets.MAVEN_P12 }}
    maven-keystore-password: ${{ secrets.MAVEN_P12_PASSWORD }}
    maven-ca-cert-b64: ${{ secrets.MTLS_CACERT }}
```

It sounds like this is a tightly-coupled set of inputs that are usually used all together or not at all.  Since I think most uses of `setup-java` would _not_ use these inputs, I'm proposing that the code that consumes those inputs goes in a separate action.  Then if we just need to set env vars for Maven to pick up the cert, then that's already supported through the YAML `env:` block.

**Comment by jsoref** [comment]
Fwiw, I agree with that conclusion.

You could actually make a composite action that wraps this action which would enable you to ensure that the version of this action that you use is compatible with your wrapper. (The downside is that you'll have to release at least as many releases as this action does in order to enable users to access updates for this action.)

If I were writing this composite action, I'd include one extra field which would skip running this action as a get-out-of-jail-free-card to enable consumers to use a newer version of this action before I released an update for my wrapper.

I'd suggest closing this ticket to show other viewers of this repository that it's maintained (I'm reviewing tickets because of the whole this repository does not appear to be healthy).

**Comment by IvanZosimov** [comment]
Hi, @tveon 👋 Thanks for the feature request, but unfortunately we have to reject it. The reason of rejection is stated in the comment https://github.com/actions/setup-java/issues/283#issuecomment-1170116239.
