### ISSUE TITLE
Custom key for caching

### ISSUE THREAD

**Issue by cemo** [actions/setup-java#287]
**Description:**
We want to use custom cache keys for our needs.

**Justification:**
We would like to reset keys by updating parent pom version of the projects. For example we are using Spring Boot Parent as parent pom. In case an upgrade in the parent version, we would like to reset cache.

**Are you willing to submit a PR?**
Yes

**Comment by dmitry-shibanov** [comment]
Hello @cemo. Thank you for your report. We would not like to implement such kind of logic, because the initial caching logic for setup-java should cover the most often use cases. If you need more flexibility with cache, we would like to recommend [actions/cache](https://github.com/actions/cache). It's relevant to setup-node [ADR](https://github.com/actions/setup-node/blob/main/docs/adrs/0000-caching-dependencies.md#goals--anti-goals).

For now I'm going to close the issue.

**Comment by cemo** [comment]
What about adding a parameter for?

https://github.com/actions/setup-java/blob/a12e082d834968c1847f782019214fadd20719f6/src/cache.ts#L28
