### ISSUE TITLE
Cache exclusion for private maven dependencies

### ISSUE THREAD

**Issue by jdfischer-cedreo** [actions/setup-java#313]
**Description:**
It would nice if we can exclude from the cache one or several directories. 
I would imagine a config parameter like this to be added:

```
  cache-exclusions:
    description: 'List of directories that you want to exclude from the cache like com/mycompany|com/myothercompany'
    required: false
```

**Justification:**
We want to exclude our jars and internal artifacts from the list of what would be cached to prevent them to be stored outside of 
our control.

**Are you willing to submit a PR?**
I doubt I have enough knowledge on action to do so, I am using it for less than a week.

**Comment by dmitry-shibanov** [comment]
Hello @jdfischer-cedreo. Thank you for your report. We would not like to implement such kind of logic, because the initial caching logic for setup-java should cover the most often use cases. If you want to use some more complex caching logic we would recommend you to use [actions/cache](https://github.com/actions/cache). It's relevant to setup-node [ADR](https://github.com/actions/setup-node/blob/main/docs/adrs/0000-caching-dependencies.md#goals--anti-goals).

For now I'm closing the issue.
