### ISSUE TITLE
Please explain why this setup is needed

### ISSUE THREAD

**Issue by MarkCallow** [actions/setup-java#371]
**Description:**
In README.md please explain why this setup is needed.

Looking at the information for Actions Windows images several versions of Java are already installed and all that seems necessary is to set JAVA_HOME to the value of the home env. var. of the Java version you wish to use, e.g. `JAVA_HOME_17_X64`. I failed to successfully do that which led me here. The first bullet in the README.md says "Downloading and setting up a requested version of Java". Since Java is already installed in the image, I wondered if I really needed this setup or if it is out of date.

**Justification:**
So newcomers will not be worried about unnecessary downloads of large packages and how this setup actually relates to the images already having Java.

**Are you willing to submit a PR?**
No. I don't know the answer.

**Comment by dmitry-shibanov** [comment]
Hello @MarkCallow. Thank you for your report. For setting up Java you need to add it to the PATH and change JAVA_HOME env variable. The action allows customers to utilize preinstalled versions of Java located in the hosted [toolcache](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Hosted-Tool-Cache) directory. Firstly the action will try to check if the version is installed. If it's so the action will use the preinstalled version. If it does not exist the action will try to download it. You can change this behaviour with [check-latest](https://github.com/actions/setup-java#check-latest) input. 

Besides, the action allows to specify [different distributions of Java](https://github.com/actions/setup-java#supported-distributions), [caching dependencies](https://github.com/actions/setup-java#caching-packages-dependencies) and [publishing](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#publishing-using-apache-maven). 

For now I'm going to close the issue because it is described in the documentation. If you have any concerns feel free to ping us.

**Comment by MarkCallow** [comment]
The part about resolving a version from the tool cache is way down the README in the section about check-latest while the very first thing the reader sees is "Downloading and Setting up ...". A clarification will be helpful such as changing the first bullet to "Setting up a requested version of Java from the tool cache, if available, downloading if necessary".

Saying that it sets up JAVA_HOME and adds the Java bin directory to PATH would also be very helpful.

Are the tools listed in, e.g., https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md in the tool cache you refer to? That page describes them as installed software so one doesn't think of them as being cached.

When I first saw this setup I truly wondered it was needed with the current images that have Java installed or if it was something from an earlier era when Java was not installed in the images.

**Comment by iTrooz** [comment]
+1, I think it would be clearer to indicate that in the bullet (for example by adding"or using the one already installed") rather than in the advanced documentation

**Comment by TWiStErRob** [comment]
Same here, I was looking for any existence of `JAVA_HOME`, but it's unclear what happens. It's only mentioned in the https://github.com/actions/setup-java#install-multiple-jdks section.
