### ISSUE TITLE
More documentation for .java-version

### ISSUE THREAD

**Issue by eygraber** [actions/setup-java#430]
**Description:**
I'm proposing adding more documentation for exactly what the format of a .java-version file is.

**Justification:**
I spent 10 minutes looking for what the format is, and what options are available to me, and I can't find anything in this repo. The docs point to jenv, but they don't have anything either.

I'm trying to specify a version and distribution following the doc's limited example of `versions with specified distribution` by using `zulu-17` but the action is failing saying that `Input required and not supplied: distribution`. I don't know if this is a bug with .java-version, or if it is working correctly, but we still have to specify a distribution in the action params.

**Comment by e-korolevskii** [comment]
Hello @eygraber!

According to the [documentation](https://github.com/actions/setup-java#usage), specifying the distribution input field is **required** for the action to work. We can only determine the version specified in the .java-version file, not the distribution.

The examples with distribution specified have been given because most often a `.java-version` file is created with `jenv` and this is just one of the possible formats for writing this file, which is defined by this program.

You can learn more about [jenv ](https://github.com/jenv/jenv#whats-jenv-)in their documentation, perhaps this will add understanding.

Have a nice day!

**Comment by e-korolevskii** [comment]
Hi @eygraber!

I just wanted to know if you managed to figure it out?

**Comment by eygraber** [comment]
I did, thank you
