### ISSUE TITLE
Check-latest is false, but still tries to resolve latest version. Then fails and just passes without setting up the requested version

### ISSUE THREAD

**Issue by kalmanbencze** [actions/setup-java#519]
**Description:**
![image](https://github.com/actions/setup-java/assets/15101592/e489e20d-d9ed-4011-9cc5-5a27a851658e)
We use v3 of the action and use it to set up adopt jdk 17. It's causing a lot of headaches that it's trying to resolve latest version, it times out and just completes without failing. There's other times where it's actually failing:
![image](https://github.com/actions/setup-java/assets/15101592/1bdf4eac-1c97-43e6-a534-a9a542925db6)

**Task version:**
v3

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  
Start a matrix of 40-50 jobs all setting up java with:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
It's guaranteed to happen to at least 5-6 times.

**Expected behavior:**
It's expected to set up java 17 from cache if `check-latest: false` is specified and not fail on "checking latest version" when it still needs to download it.

**Actual behavior:**
`check-latest: false` is ignored as seen in screenshot #1, and when a very frequent timeout happens, the acton passes successfully.

**Comment by kalmanbencze** [comment]
upgrading to 3.12.0 may have fixed the issue, I'll close this if it doesn't reproduce anymore.

**Comment by IvanZosimov** [comment]
Hi, @kalmanbencze 👋 Thanks for the issue, we will take a look!

**Comment by IvanZosimov** [comment]
Hi, @kalmanbencze 👋 I tried to reproduce the issue, but unfortunately without luck. May I ask you to turn the debug mode on (link to guide how to do this can be found [here](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging)) and provide us with additional information about the failed runs (links or logs would be appreciated).

**Comment by IvanZosimov** [comment]
Just a gentle ping, @kalmanbencze 📟

**Comment by kalmanbencze** [comment]
sorry I was afk for a bit, will do and report back.

**Comment by kalmanbencze** [comment]
[24_build  (featurefamilyrewardsfamilyrewards-implementation).txt](https://github.com/actions/setup-java/files/12539723/24_build.featurefamilyrewardsfamilyrewards-implementation.txt)
maybe I haven't enabled the debug logging properly? I did what the guide said about adding the secret `ACTIONS_RUNNER_DEBUG` with `true`

**Comment by Pogie10** [comment]
WALA AKO PAKE UNTOG NYO ULO NYO SA PADER

**Comment by gowridurgad** [comment]
Hi @kalmanbencze, We have conducted tests with a matrix of 40-50 jobs all setting up Java with the following configuration:
```
   distribution: adopt
   java-version: 17
   cache: gradle
```
We did not encounter any timeout errors during our tests. Attached is a screenshot for your reference.
**Regarding the check-latest: false configuration**:
When the check-latest flag is set to false, the action will first attempt to find and use a version of Java that is already cached locally on the runner.
If the specific version of Java is not found in the local cache, the action will then download the required version.
For more information, please visit https://github.com/actions/setup-java. 
In your case, check-latest: false still tries to resolve the latest version because the latest version is cached on the runner. You can check the Java versions that are already cached locally on the runner [here](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#java).

Could you please provide additional details or specific configurations that might help us reproduce the problem? 

<img width="1061" alt="Screenshot 2024-11-20 at 8 20 42 AM" src="https://github.com/user-attachments/assets/0e86caa6-dab2-4e10-9016-ab01eb0c3ff5">

<img width="1616" alt="Screenshot 2024-11-20 at 9 39 14 AM" src="https://github.com/user-attachments/assets/39e87e06-a1bc-424b-b5d3-b42c9f23c7ea">

**Comment by kalmanbencze** [comment]
Thank you for taking another look, but if you cannot reproduce it, then it must mean the circumstances were different in some way a year ago that affected the outcome. In the meantime we have stopped seeing the issue / moved on. This ticket can be closed.
