### ISSUE TITLE
List of supported Java versions

### ISSUE THREAD

**Issue by rdk** [actions/setup-java#521]
Is there complete a list of JDK versions that are supported at the moment? 
How do I check if specific JDK  installation+version is supported?

For example, I would like to know if I can use some/any Java 21 Early Access build.

**Comment by dmitry-shibanov** [comment]
Hello @rdk. Thank you for your report. I think for that case it will be better to check [official sites](https://github.com/actions/setup-java#supported-distributions) to confirm that versions are available. We do not want to update documentation regarding to all distributions because it will lead to often changes of it and possibly to misleading information because of amount of distributions and their supported versions. 

For now I'm going to close the issue.
