### ISSUE TITLE
Forked repo fails to successfully execute setup-java

### ISSUE THREAD

**Issue by HughPowell** [actions/setup-java#536]
**Description:**
Having forked the [metosin/spec-tools](https://github.com/metosin/spec-tools) repo, which has executed and successfully run the [setup-java](https://github.com/metosin/spec-tools/actions/runs/5998840739/job/16267836940) action, the action fails on my repo, [HughPowell/spec-tools](https://github.com/HughPowell/spec-tools), [because it can't find a pom.xml file](https://github.com/HughPowell/spec-tools/actions/runs/6243920502/job/16950067716).
Both the [original repo's workflow](https://github.com/metosin/spec-tools/blob/master/.github/workflows/release.yml) and [mine](https://github.com/HughPowell/spec-tools/blob/master/.github/workflows/release.yml) are identical.

**Task version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
- Fork my [repo](https://github.com/HughPowell/spec-tools)
- Create a [personal access token (classic)](https://github.com/settings/tokens) with the `repo` scope (including all children).
- Clone your fork and `cd` into the repo
- Run `GITHUB_TOKEN=<access token created above> ./scripts/releases` (if you need to re-run this step then delete the latest `Releases` on the front page of the repo).
- Enter `y` when prompted
- Go to the `Actions` tab in GitHub and notice that the `setup-java` action fails

**Expected behavior:**
The `setup-java` action succeeds. 

**Actual behavior:**
The `setup-java` action fails.

**Comment by IvanZosimov** [comment]
Hi, @HughPowell 👋 Thanks for the issue, I've just checked the original repository you forked and the workflow you pointed out [failed there as well](https://github.com/metosin/spec-tools/actions/workflows/release.yml) because of the same reason. As you can see, only the last run was successful, as the owner of the repo [disabled](https://github.com/metosin/spec-tools/actions/runs/5998840739/workflow) the cache option of the action. 
So there are two options for how to fix this problem:
1. disable cache option of the action ([this](https://github.com/actions/setup-java#caching-packages-dependencies) chapter of readme can be helpful)
2. add `pom.xml` file to the repo.

I hope this will help to solve your problem, now I'm going to close this issue. If you have any additional questions, feel free to ping me.

**Comment by HughPowell** [comment]
Hi @IvanZosimov , thanks for following up so quickly on this. It's now fixed. Much appreciated :bow:
