### ISSUE TITLE
Dependency downloaded but module not found

### ISSUE THREAD

**Issue by LingkKang** [actions/setup-java#569]
### Description

To simply put, Maven have downloaded dependencies, but failed at compiling, saying that it can not find module.

I'm using GSON on my project, it runs well locally, but on GitHub action, Maven keeps reporting the error.

```
Error:  COMPILATION ERROR : 
Error:  /home/runner/work/gson-ci/gson-ci/src/main/java/module-info.java:[3,24] module not found: com.google.gson
```

Although accroding to the log, it have downloaded dependencies successfully.

### Reproduce

I've abstracted away irrelevant things, left this small repo: [LingkKang/gson-ci](https://github.com/LingkKang/gson-ci), and the action still failed to run:

- [Java CI with Maven · LingkKang/gson-ci@c3f0f74](https://github.com/LingkKang/gson-ci/actions/runs/7201889629/job/19618915867)
- [Java CI with Maven · LingkKang/gson-ci@7272b1d](https://github.com/LingkKang/gson-ci/actions/runs/7202287420/job/19620119479) (with Maven `-X` and `-e` flags)

**Expected behavior:**

Pass the CI.

**Actual behavior:**

CI failed at Maven compiling.

### Task version

```
uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven
        java-package: jdk+fx
```

Never tried other distributions because I'm going to use JavaFX.

### Platform

- [x] Ubuntu
- [ ] macOS (not tested
- [x] Windows

### Runner type

- [x] Hosted
- [ ] Self-hosted

--- 

I'm not sure is this really a bug of `setup-java`, it might due to different Maven version or GSON, but as it can build on local machine, I suspect it was caused by `setup-java`. 😢

**Comment by IvanZosimov** [comment]
Hi, @LingkKang 👋 Thanks for the bug report, we will investigate the issue and get back to you with updates.

**Comment by LingkKang** [comment]
This is probably because of too old Maven version.

I tried to set up JDK and Maven (using `3.9.6`, the latest stable version) manually, and the workflow successed.

A naive demo can be found here:
 - new CI config [ci.yml at main](https://github.com/LingkKang/gson-ci/blob/main/.github/workflows/ci.yml)
 - the running result [Run Maven compile · LingkKang/gson-ci@108f116](https://github.com/LingkKang/gson-ci/actions/runs/7228060204).

Additionally, answer of this StackOverflow question 👇 suggested that newer version of Maven compiler plugin can fix it. I suspect they are somehow related.

[java - Maven dependency module not found - Stack Overflow](https://stackoverflow.com/questions/50451220/maven-dependency-module-not-found)

Hope this can help :D

**Comment by aparnajyothi-y** [comment]
Hello @LingkKang, I apologize for the delayed response. Thank you for confirming that the issue was resolved with the latest Maven versions. We have also tested it with the latest stable version, 3.12.1, and the run was successful. Please find the screenshots for reference.
We will proceed to close the issue, as it has been resolved and confirmed.
Please feel free to reach us to reopen the issue in case of any concerns.
<img width="1022" alt="Screenshot 2024-11-04 at 6 28 02 PM" src="https://github.com/user-attachments/assets/d572ea58-d9c3-412b-9557-f0b97be9efe3">
<img width="1022" alt="Screenshot 2024-11-04 at 6 30 20 PM" src="https://github.com/user-attachments/assets/34f1df55-ef68-42c3-8008-c849c3060e45">
