### ISSUE TITLE
Rename default branch

### ISSUE THREAD

**Issue by andymckay** [actions/setup-java#80]
👋 This issue is to track the move over to using `main` as the default branch for this repo. We’d love your team's help in completing this transition.

**Do not remove your old default branch**, customers are going to be using it. We will be sending messages out about these changes, but if you want to message in your repository, that's fine as well.

- [x] Create a `main` branch.
- [x] You might need to rebase any pull requests you want to merge before changing the default branch.
- [x] Change the default branch in settings to `main`.
- [x] Update any documentation in this repo to refer to the new branch name, although using the version tag is still preferred.
- [x] Check that this Action works correctly for users who have a repository with a custom default branch name.
- [x] Close this issue and celebrate 🎉

We are aiming to complete this work by ~July 17th~ July 24th.

**Comment by joschi** [comment]
@andymckay Please keep in mind that there might be some users referencing `actions/java@master` in their workflows and this change would break their builds.

Unfortunately the GitHub code search doesn't yield a useful result because `@` is being used to tokenize the input:
[Search result for `language:yaml path:".github/workflows" "actions/setup-java" +master`](https://github.com/search?p=1&q=language%3Ayaml+path%3A%22.github%2Fworkflows%22+%22actions%2Fsetup-java%22+%2Bmaster&type=Code)

**Comment by konradpabjan** [comment]
@joschi Only the default branch will be changed to `main`. The `@master` branch won't be removed any time soon (no plans at all currently), we would break ALOT of users if we did that just looking at internal telemetry.

A few first party actions have already changed to `main` such as `upload-artifact`, `download-artifact` and `checkout`. Expect no side-effects. Users tied to `@master` just won't get the latest updates unless they switch to `@main` or a specific tag.

**Comment by joschi** [comment]
@konradpabjan Thanks a lot for the clarification!

**Comment by konradpabjan** [comment]
I've updated the branch to `main`. I've merged in two PRs beforehand however there are still some big ones that have been languishing in sadness in despair and I need to find some time to try take a look at them😞 those will have to be rebased in the future
