### ISSUE TITLE
Add libjvm.so to LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by stanislav-tkach** [actions/setup-java#99]
I'm using this github action to setup Java for a non-java application that uses JNI and I'm getting the following error:
> error while loading shared libraries: libjvm.so

Is it possible to (perhaps optionally) add this library to `LD_LIBRARY_PATH`? Additionally, on Windows it should be `PATH`.

**Comment by giltene** [comment]
Changing the LD_LIBRARY_PATH (or equivalent) in ways that don’t normally happen when pointing to a JDK seems to me to be the wrong thing generically, and can have seriously surprising side effects on existing applications (e.g. ones that would later switch JAVA_HOME to something else without changing LD_LIBRARY_PATH themselves, which is quite common).

It may be what yoyr specific application needs, but that application would have to have been doing that anyway to work in any normal environment where JAVA_HOME points to the JDK base and libjvm.so is not in the LD_LIBRARY_PATH. Most likely (IMO),  your environment is setting LD_LIBRARY_PATH (from JAVA_HOME) too early, before the setup-java action was called. If I’m right, then moving whatever is setting that for you to happen after the setup-java action executes would be the way to go.

**Comment by stanislav-tkach** [comment]
Perhaps I'm doing something wrong, but my situation is the following: I have a library (it is JNI bindings for the Rust language) that has an optional functionality that relies on `libjvm.so` being available. It is the user's responsibility to perform the correct setup in a regular environment, but I need to test it on CI. Previously we have used Travis (that provides a suitable environment for our testing) and Appveyor (in that case a specific library needs to be added to the path manually).

I understand that perhaps it isn't a responsibility of this action, but the path to the `libjvm.so` will be different depending on the architecture and probably Java version. Sorry for bothering you, but can you give any advice on this? Isn't there a standard way to do this?

**Comment by giltene** [comment]
You would do it in whatever way you instruct your users to do it. Most likely by e.g. adding (appending? pretending? depends on your requirement) $JAVA_HOME/lib/server/libjvm.so to LD_LIBRARY_PATH. Yes, the conventions for that relative path, and the name of the library, and the name of the variable to add it to can all vary by OS and potentially java version. But that’s life with native code (which will already be stringy dependent on all those same variables).

I can see some logic for asking for a helpful “have the action set an environment variable (like SETUP_JAVA_LIBJVM_LOCATION) that tells you where libjvm is” so that you can then use that in your later scripting to set something on the LD_LIBRARY_PATH  (or equivalent). This would require the action to know where that location is for any JDK it downloads. It is possible to do, but there is no actual standard for this across java versions, OSs, or even JDK distributions (just some conventions that seem to be followed), and as binary download locations and APIs for locating JDKs in various distros currently don’t provide an answer to that question, it is likely to be fairly fragile.

**Comment by stanislav-tkach** [comment]
Thanks for the explanation. I'm going to do that on my side. I suppose this issue can be closed?..

**Comment by dmitry-shibanov** [comment]
Hello @giltene. Thank you for detailed explanation.
